
document.write("<scr"+"ipt language=\"javascript\" src=\"http://aka-cdn-ns.adtech.de/dt/common/DAC.js\"></scr"+"ipt>\n");

document.write("<scr"+"ipt type=\"text/javascript\" src=\"http://aka-cdn-ns.adtech.de/apps/399/Ad14266767St3Sz16Sq109567909V19Id1/extFile1.js\"></scr"+"ipt>\n");
document.write("<head>\n");
document.write("<style>\n");
document.write("</style>\n");
document.write("</head>\n");

document.write("    \n");
document.write("    <style type=\"text/css\">\n");
document.write("@font-face {\n");
document.write("font-family: \"Publico Headline\";\n");
document.write("src: url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Medium-Web.eot\");\n");
document.write("src: url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Medium-Web.eot?#iefix\") format(\"embedded-opentype\"),\n");
document.write("url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Medium-Web.woff\") format(\"woff\"),\n");
document.write("url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Medium-Web.ttf\") format(\"truetype\"),\n");
document.write("url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Medium-Web.svg\") format(\"svg\");\n");
document.write("font-weight: normal;\n");
document.write("font-style: normal;\n");
document.write("}\n");
document.write("@font-face {\n");
document.write("font-family: \"Publico Headline\";\n");
document.write("src: url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Bold-Web.eot\");\n");
document.write("src: url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Bold-Web.eot?#iefix\") format(\"embedded-opentype\"),\n");
document.write("url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Bold-Web.woff\") format(\"woff\"),\n");
document.write("url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Bold-Web.ttf\") format(\"truetype\"),\n");
document.write("url(\"http://www.tagesanzeiger.ch/css/fonts/publico/PublicoHeadline-Bold-Web.svg\") format(\"svg\");\n");
document.write("font-weight: bold;\n");
document.write("font-style: normal;\n");
document.write("}\n");
document.write("html, body {\n");
document.write("margin: 0;\n");
document.write("padding: 0;\n");
document.write("}\n");
document.write(".surroundingbox {\n");
document.write("overflow: hidden;\n");
document.write("width:100%;\n");
document.write("position: relative;\n");
document.write("}\n");
document.write(".innerbox {\n");
document.write("}\n");
document.write(".title {\n");
document.write("float: left;\n");
document.write("cursor:pointer;\n");
document.write("color : rgb(0, 122, 191);\n");
document.write("font-family: \"Publico Headline\";\n");
document.write("letter-spacing: -.03rem;\n");
document.write("margin: 0 0 .2rem;\n");
document.write("font-size: 22px;\n");
document.write("line-height: 24px;\n");
document.write("margin-bottom: 5px;\n");
document.write("}\n");
document.write(".title a:link, .title a:visited, .title a:active {\n");
document.write("font-weight: normal;\n");
document.write("color: black;\n");
document.write("text-decoration: none;\n");
document.write("}\n");
document.write(".title a:hover {\n");
document.write("text-decoration: underline;\n");
document.write("}\n");
document.write(".text{\n");
document.write("float: left;\n");
document.write("font-weight: lighter;\n");
document.write("width: 100%;\n");
document.write("display: block;\n");
document.write("-webkit-margin-after: 1em;\n");
document.write("-webkit-margin-start: 0px;\n");
document.write("-webkit-margin-end: 0px;\n");
document.write("font-size: 15px;\n");
document.write("line-height: 20px;\n");
document.write("font-family: Georgia;\n");
document.write("margin-bottom: 0px;\n");
document.write("}\n");
document.write(".text a:link, .text a:visited, .text a:active{\n");
document.write("text-decoration: none;\n");
document.write("color:rgb(51, 51, 51);\n");
document.write("}\n");
document.write("img.adimage{\n");
document.write("width: 100%;\n");
document.write("display: inline-block;\n");
document.write("float: left;\n");
document.write("margin: 0 0.65rem 0.75rem 0;\n");
document.write("}\n");
document.write(".caption {\n");
document.write("z-index: 5;\n");
document.write("position: absolute;\n");
document.write("text-align: center;\n");
document.write("right:0;\n");
document.write("width:45px;\n");
document.write("font-size: 10px;\n");
document.write("background: dodgerblue;\n");
document.write("color:white;\n");
document.write("}\n");
document.write(".trackingpixel{\n");
document.write("display:none;\n");
document.write("}\n");
document.write("</style>\n");

document.write("    <div class=\"surroundingbox\">\n");
document.write("      <div class=\"caption\">Anzeige</div>\n");
document.write("      <div id=\"innerbox\" class=\"innerbox\">\n");
document.write("        <div id=\"6058078\">\n");
document.write("        </div>\n");
document.write("      </div>\n");
document.write("    </div>\n");
document.write("<scr"+"ipt type=\"text/javascript\" src=\"http://aka-cdn-ns.adtech.de/apps/399/Ad14266767St3Sz16Sq109567909V19Id1/extFile2.js\"></scr"+"ipt>\n");


