version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    # build: .
    hostname: imap
    domainname: gmail.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - ./config/:/tmp/docker-mailserver/
      - ../websites/zwish_email/emails/:/mails/

volumes:
  maildata:
    driver: local
