#!/usr/bin/env bash
(
  echo To: jonaswid_92@gmail.com
  echo From: noreply@zwish.ch
  echo "Content-Type: text/html; "
  echo Subject: $1
  echo "MIME-Version: 1.0"
  echo
  cat $2
) | docker exec -i mail sendmail -t
