(function(a,z,x){function I(c,l){c.super_=l;e.prototype=l.prototype;c.prototype=new e;c.prototype.constructor=c}function e(){}function h(c,l){for(var A in l)l.hasOwnProperty(A)&&(c[A]=l[A]);return c}function v(c,l){return(l=l||x)&&l.getElementById&&l.getElementById(c)}function E(c,l){var A=l?c.substr?v(c):c:x;return A?A.getElementsByTagName(l||c):[]}function B(c,l){return~(" "+c.className+" ").indexOf(" "+l+" ")}function F(c,l){B(c,l)&&(c.className=(" "+c.className+" ").replace(" "+l+" "," ").slice(1,
-1),F(c,l))}function P(c){var l=c.offsetTop,A=c.offsetLeft,f,a=b.curCSS,d="static"!=a(c,"position");l||(l=(parseFloat(a(c,"marginTop"))||0)+(d?parseFloat(a(c,"top"))||0:0));A||(A=(parseFloat(a(c,"marginLeft"))||0)+(d?parseFloat(a(c,"left"))||0:0));d&&c.getBoundingClientRect&&(f=b.offset(c,!0));!l&&f&&(l=f.top);!A&&f&&(A=f.left);return{top:l,left:A}}function J(c){var l={relativeX:c[H[0]],relativeY:c[H[1]]};if(null==c.pageX&&null!=c.clientX){var A=x.documentElement,f=x.body;l.pageX=c.clientX+(A&&A.scrollLeft||
f.scrollLeft||0);l.pageY=c.clientY+(A&&A.scrollTop||f.scrollTop||0)}else l.pageX=c.pageX,l.pageY=c.pageY;return l}function u(c,l){if(!(c=c.parentNode))return!1;var A=c.ownerDocument,f=A.body,a=b.curCSS,d;l&&(l+=1);if(z.$sf)return!0;if(b.isIE&&(8>A.documentMode||"BackCompat"==A.compatMode))return!1;for(;c&&c!=f;){if("hidden"==a(c,"overflow"))return!1;if("fixed"==a(c,"position"))break;else if(l&&(d=parseInt(a(c,"z-index"),10))&&d<l)return!1;c=c.parentNode}return!0}function p(){for(var c=0,l=[];c<V.length;c++)"complete"!=
V[c].document.readyState&&l.push(V[c]);if(!(V=l).length||3E4<(new Date).getTime()-K){L=clearInterval(L);for(c=0;c<W.length;c++)W[c]();W=[];V=[]}}function r(c,l){var A=Math.max(c.x,l.x),f=Math.max(c.y,l.y),a=Math.min(c.x+c.width,l.x+l.width)-A,b=Math.min(c.y+c.height,l.y+l.height)-f;return 0<a&&0<b?{x:A,y:f,width:a,height:b}:{x:0,y:0,width:0,height:0}}function y(c,l,A,f){var a=function(c){f&&f.apply(c,arguments)},d=E(A,"head"),d=d&&d[0];if(!d)try{throw Error("Can't find head tag.");}catch(k){a(k)}var q=
l.src||l.href,w=q.replace(/[^\da-z_-]/gi,"_"),G=A.adformId||b.gid("doc_"),g=G+"|"+w,n=X[g],w=b.byTag(A,c),m=0,D=w.length;A.adformId=A.adformId||G;if(n)n.loaded?a():n.callbacks.push(a);else{for(;m<D;++m)if(w[m].src==q||w[m].href==q){a();return}X[g]=n={doc:A,src:q,callbacks:[a]};var t=A.createElement(c),e;h(t,l);f&&(e=function(c){t.onload=t.onreadystatechange=t.onerror=null;c?X[g]=null:n.loaded=1;var l=n.callbacks;m=0;for(D=l.length;m<D;++m)l[m](c)},t.onload=function(){e()},t.onreadystatechange=function(){"complete"==
t.readyState&&e()},t.onerror=function(){try{throw Error("Failed to load script: "+q);}catch(c){e(c)}});setTimeout(function(){d.insertBefore(t,d.firstChild)},400)}}a.Log||(a.Log={});a.Log.pushMessage||(a.Log.pushMessage=function(){});a.Log.sendMessage||(a.Log.sendMessage=function(){});a.RMB=a.RMB||{};var g=a.RMB,b=g.lib||(g.lib={});a.lib||(a.lib=b);b.inherit=I;b.define=function(c,l,f){f&&I(c,l);f(c,c.prototype)};b.gid=function(c){var l=+new Date;return(c||"")+(l+l*~~(1E4*Math.random())).toString(36)};
b.byId=v;b.byTag=E;b.bind=function(c,l){return function(){return l.apply(c,arguments)}};b.extend=h;b.isMouseLeave=function(c,l){if(!c||"mouseout"!=c.type)return!0;for(var f=c.relatedTarget||c.toElement,a,d=l.length;f;){for(a=0;a<d;a++)if(l[a]==f)return!1;f=f.parentNode}return!0};b.singleCall=function(c){function l(){b=!1;var c=a,l=f,k=d;f=a=d=null;c&&c.apply(l,k)}var f,a,d,b;return function(k,q){f=k;a=q;d=w.call(arguments,2);q&&!b?b=setTimeout(l,c):!q&&b&&(clearTimeout(b),b=!1)}};b.onload=function(c,
l){try{do{if(c[Y])break;c[Y]=!0;"complete"!=c.document.readyState&&(V.push(c),L||(K=(new Date).getTime(),L=setInterval(p,200)))}while(c!=c.parent&&(c=c.parent))}catch(f){}L?W.push(l):setTimeout(l,0)};b.overlap=r;b.overlapElem=function(c,l){var f=b.offset(c),a=b.offset(l);return r({x:f.left,y:f.top,width:c.offsetWidth,height:c.offsetHeight},{x:a.left,y:a.top,width:l.offsetWidth,height:l.offsetHeight})};b.hasClass=B;b.addClass=function(c,l){B(c,l)||(c.className+=" "+l)};b.removeClass=F;b.loadScript=
function(c,l,f){y("script",{src:l,type:"text/javascript"},c,f)};b.loadCSS=function(c,l){y("link",{href:l,type:"text/css",rel:"stylesheet"},c)};b.navigator=z.navigator;b.isTMX=function(c){try{var l=c.document,f=l&&l.body;return f&&B(f,"tmx")}catch(a){}return!1};b.isolate=function(c,f){var a=c.__adform_isolate;if(!a){var d=c.document,a=E(d,"head")[0],d=d.createElement("script");d.type="text/javascript";d.text='function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';a.insertBefore(d,
a.firstChild);a.removeChild(d);a=c.__adform_isolate}a?a(f):(new Function("window","("+f+")(window)"))(c)};var w=Array.prototype.slice;b.addEvent=function(c,f,a){return c[R]?c[R](f,a,!1):c[d]?c[d]("on"+f,a):!1};b.removeEvent=function(c,f,a){return c[C]?c[C](f,a,!1):c[q]?c[q]("on"+f,a):!1};var R="addEventListener",C="removeEventListener",d="attachEvent",q="detachEvent",n=/([A-Z])/g,D=/^-?\d+(?:px)?$/i,t=/^-?\d/;a=x.defaultView;b.curCSS=a&&a.getComputedStyle?function(c,f){var a=c.ownerDocument.defaultView;
if(a&&(a=a.getComputedStyle(c,null)))return a.getPropertyValue(f.replace(n,"-$1").toLowerCase())||c.style[f]}:x.documentElement.currentStyle&&function(c,f){var a,d,b,k=c.currentStyle&&c.currentStyle[f];if(!D.test(k)&&t.test(k)){a=(b=c.style).left;if(d=c.runtimeStyle&&c.runtimeStyle.left)c.runtimeStyle.left=c.currentStyle.left;b.left="fontSize"===f?"1em":k||0;k=b.pixelLeft+"px";b.left=a;d&&(c.runtimeStyle.left=d)}return""===k?"auto":k};var m=function(){function c(){return c}var f=x.body,a=x.createElement("div"),
d;d=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();a.innerHTML='<div style="'+d+'visibility:hidden"><div style="'+d+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+d+'"><div style="'+d+'position:fixed;top:20px;"></div></div><div style="'+d+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+d+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';
f.insertBefore(a=a.firstChild,f.firstChild);d=a.childNodes;c.dnab=5!==d[0].firstChild.offsetTop;c.sfp=20===d[1].firstChild.offsetTop;c.sbfonv=-5===d[2].firstChild.offsetTop;c.dabftac=5===E(a,"td").offsetTop;f.removeChild(a);f=a=d=null;return m=c},M=/^t(?:able|d|h)$/i;b.offsetFromWindow=function(c){var f,a,d,k;a=c&&c.ownerDocument;if(!a)return null;d=a.documentElement;if("getBoundingClientRect"in d){try{f=c.getBoundingClientRect(),k=d.getBoundingClientRect()}catch(q){}if(!f)return{top:0,left:0};if(0<
k.left||0<k.top)f.top-=k.top,f.left-=k.left;return{top:f.top,left:f.left}}f=a.defaultView||a.parentWindow;k=a.body;if(c===a.body)return P(c);c=b.offset(c);a=f&&f.pageYOffset||d.scrollTop||k.scrollTop;d=f&&f.pageXOffset||d.scrollLeft||k.scrollLeft;c.top-=a;c.left-=d;return c};b.offset="getBoundingClientRect"in x.documentElement?function(c,f){var a,d=c&&c.ownerDocument;if(!d)return null;if(!f&&c===d.body)return P(c);try{a=c.getBoundingClientRect()}catch(b){}if(!a)return{top:0,left:0};var k=d.body,d=
d.documentElement;return{top:a.top+(d.scrollTop||k.scrollTop)-(d.clientTop||k.clientTop||0),left:a.left+(d.scrollLeft||k.scrollLeft)-(d.clientLeft||k.clientLeft||0)}}:function(c){var f=c&&c.ownerDocument;if(!f)return null;if(c===f.body)return P(c);var a,d=c.offsetParent,b=f.documentElement,k=f.body;a=(f=f.defaultView)?f.getComputedStyle(c,null):c.currentStyle;for(var q=c.offsetTop,w=c.offsetLeft,n=m();(c=c.parentNode)&&c!==k&&c!==b&&(!n.sfp||"fixed"!==a.position);)a=f?f.getComputedStyle(c,null):c.currentStyle,
q-=c.scrollTop,w-=c.scrollLeft,c===d&&(q+=c.offsetTop,w+=c.offsetLeft,!n.dnab||n.dabftac&&M.test(c.nodeName)||(q+=parseFloat(a.borderTopWidth)||0,w+=parseFloat(a.borderLeftWidth)||0),d=c.offsetParent),n.sbfonv&&"visible"!==a.overflow&&(q+=parseFloat(a.borderTopWidth)||0,w+=parseFloat(a.borderLeftWidth)||0);if("relative"===a.position||"static"===a.position)q+=k.offsetTop,w+=k.offsetLeft;n.sfp&&"fixed"===a.position&&(q+=Math.max(b.scrollTop,k.scrollTop),w+=Math.max(b.scrollLeft,k.scrollLeft));return{top:q,
left:w}};b.client=function(c){var f,a,d,k;c=c.ownerDocument||c;a=c.defaultView||c.parentWindow;d=c.documentElement;k=c.body;a.innerWidth?(c=a.innerWidth,f=a.innerHeight):d?(c=d.clientWidth,f=d.clientHeight,c&&k.clientHeight==k.offsetHeight||(c=Math.min(c||123456789,k.clientWidth||123456789),f=Math.min(f||123456789,k.clientHeight||123456789))):(c=k.clientWidth,f=k.clientHeight);return{left:a&&a.pageXOffset||d&&d.scrollLeft||k&&k.scrollLeft||0,top:a&&a.pageYOffset||d&&d.scrollTop||k&&k.scrollTop||0,
width:c,height:f}};b.isArray=Array.isArray||function(c){return"[object Array]"==Object.prototype.toString.call(c)};var H=[["offsetX","offsetY"],["layerX","layerY"]];b.getMousePos=function(c){for(var f;f=H.shift();)if("undefined"!=typeof c[f[0]]){H=f;break}f||(H=["x","y"]);b.getMousePos=J;return J(c)};var U=x.createElement("div");b.html=function(c,f){var a=!f&&U||f.createElement("div");a.innerHTML=c;return a.firstChild&&a.removeChild(a.firstChild)};a=b.navigator;var S=a.vendor;a=a.userAgent;var N=
/Apple Computer/i.test(S),g=/Google/i.test(S),T=b.isIPad=/iPad/i.test(a),k=b.isIPhone=/iPhone/i.test(a),G=b.isIOS=T||k,Q=b.isTouch="ontouchstart"in x.documentElement||"ontouchstart"in z,T=b.isOrientation="orientation"in z,k=b.isAndroid=!G&&/Android/i.test(a);b.isAndroidApp=k&&!/^(?:Opera|Mozilla)/i.test(a);var O;b.isIOSF=G&&(O=/\sos\s(\d+)_\d+/i.exec(a))&&(O=4<O[1]>>0);var f=b.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(a)||Q;O=b.isIE=/msie|Trident/i.test(a);Q=b.isFF=/Firefox[\/.]+[^\s]/i.test(a);b.isMACOS=
/Mac OS X/i.test(a);(b.isWinPhone=O&&f&&/Phone/gi.test(a))&&(f=/Windows Phone (OS )?(\d+[\.\d]*)/i.exec(a))&&f[2]&&(b.winPhoneVer=parseFloat(f[2]));var f=b.isOpera=/Opera/i.test(a),Z=b.isOperaMobile=/Opera\s(?!Mini)/i.test(a),aa=b.isOperaMini=/Opera\sMini/i.test(a),S=b.isOperaWebKit=/OPR/i.test(a)&&/Opera Software/i.test(S),G=b.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(a)&&(G?N:g),N=b.isSafari=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&N,g=b.isInternet=k&&!G&&T&&/Safari\/[\.\d]+$/i.test(a)&&
g;b.isEdge=/Edge\/[\.\d]+$/i.test(a);b.isAfmaSDK=/afma-sdk/i.test(a);var ba=O?"msie":Q?"firefox":Z?"operaMobile":aa?"operaMini":f?"opera":S?"operaWebKit":G?"chrome":N?"safari":g?"internet":!1;b.browser=function(){return ba};b.isIE&&("Microsoft Internet Explorer"==b.navigator.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))&&(b.ieVersion=parseFloat(RegExp.$1));b.testPlace=b.isIE&&8>b.ieVersion?function(){return!1}:u;b.isSafari&&(a=/Version.([\d.]+)/.exec(a),b.safariVersion=parseFloat(a&&
a[1]));var V=[],W=[],Y="__adform_onload",L,K,X={}})(Adform=window.Adform||{},window,document);
(function(a){function z(){}a.RMB=a.RMB||{};a.RMB.EventEmitter=z;var x=Array.prototype.slice;a=z.prototype;a.emit=function(a){var e=this._events,h=!1,v=arguments;if(e&&(e=e[a]))if("function"==typeof e){switch(v.length){case 1:e.call(this);break;case 2:e.call(this,v[1]);break;case 3:e.call(this,v[1],v[2]);break;case 4:e.call(this,v[1],v[2],v[3]);break;default:e.apply(this,x.call(v,1))}h=!0}else if(e.length){for(var v=x.call(v,1),e=e.slice(),h=0,E=e.length;h<E;h++)e[h].apply(this,v);h=!0}else delete this._events[a];
return h};a.on=function(a,e){this._events||(this._events={});this.emit("newListener",a,e);var h=this._events;h[a]?"function"==typeof h[a]?h[a]=[h[a],e]:h[a].push(e):h[a]=e;return this};a.once=function(a,e){var h=e._once;h?h._times++:(h=e._once=function(){this.off(a,h);1>--h._times&&delete e._once;return e.apply(this,arguments)},h._times=1);return this.on(a,h)};a.off=function(a,e){if(!this._events||!this._events[a])return this;var h=this._events,v=h[a];if(v==e)return delete h[a],this;e&&e._once&&this.off(e._once);
if("function"==typeof v)return this;if(2>v.length&&v[0]==e)return delete h[a],this;for(var x=0,B=v.length,F=[];x<B;x++)v[x]!=e&&F.push(v[x]);F.length!=B&&(F.length?h[a]=F:delete h[a]);return this};a.clear=function(a){a?this._events&&this._events[a]&&delete this._events[a]:delete this._events;return this};a.list=function(a){this._events||(this._events={});var e=this._events;e[a]?"function"==typeof e[a]&&(e[a]=[e[a]]):e[a]=[];return e[a]}})(Adform=window.Adform||{});
(function(a,z,x){function I(a){return parseInt(a,10)?a:0}function e(){}function h(a,e,h){function u(){y=!1;var a=r;r=[];h(function(b){for(var w=0;w<a.length;w++)if(b)a[w][1](b);else p(a[w][0],a[w][1])})}function p(g,b){var w=!1;e(g,function(){w=!0;b.apply(this,arguments)});w||(r.push([g,b]),y||(y=setTimeout(u,a)))}var r=[],y=!1;return p}function v(a,e,h){var u=a["@id"]||0,p;p=a["@pdata"]||"";var r,y,g={$id:u,$name:a["@name"]||"default",$link:h.replace(/adfibeg=\d+/,p?"pdata="+p:"adfibeg="+u),$pdata:p};
if(a.TextVars)for(h=0,u=a.TextVars.TextVar,p=u.length,B.isArray(u)||(u=[u],p=1);h<p;h++)r=u[h],y=r["@name"],r=r["@value"],g[y]=r,"product_deeplink"==y&&(g.$link+=";cpdir="+encodeURIComponent(r));if(a.Graphics)for(h=0,u=a.Graphics.Graphic,p=u.length,B.isArray(u)||(u=[u],p=1);h<p;h++)r=u[h],g[r["@name"]]=e+r["@value"]+"?assetID="+r["@assetID"]+"&av="+r["@av"];return g}var E=a.AdMessage||(a.AdMessage={}),B=a.lib;E.build=function(a){function x(){var a=N?N.length:0;return{total:a,totalPages:Math.ceil(a/
y),pageSize:y,ids:N||[],limit:r}}function J(a,k,b){E.load(D[a]+"&"+k,function(a,f){if(a)b(a);else{var k=q,w=d,n=f.root,m={};if(n.TextVars||n.Graphics)m[0]=v(n,k,w);if(n.Groups){var G=0,c=n.Groups.Group,l;B.isArray(c)||(c=[c]);for(l=c.length;G<l;G++){var t=v(c[G],k,w);m[t.$id]=t}}k=n.GroupIds?n.GroupIds.split(","):[];b(null,{ids:k,items:m,total:k.length})}})}function u(a){if(a)for(var d in a)a.hasOwnProperty(d)&&(S[d]=a[d])}var p=z.dhtml&&dhtml.getVar()||{},r=I(a.limit)||100,y=I(a.pageSize)||1,g=I(a.cid||
p.cid),b=I(a.tid||p.tid),w=I(a.tv||p.tv)||+new Date,R=I(a.bn||p.bn),C=a.gid||p.gid||0,d=a.clickTAG||"",q=(a.statics||a.domain||p.staticDomain||p.domain).replace(/\/+$/,""),n=(a.domain||p.domain).replace(/(\w+:\/\/[^\/]+\/).*/,"$1"),D={adMessage:n+"Serving/AdMessage/?",recommendations:n+"dco/recommendations/?",products:n+"dco/products/?"},g="aid="+g+"&tid="+b+"&tv="+w,b=I(a.icid||p.icid),w=I(a.rotseqno||p.rotseqno),n=a.smid||p.smid,t=a.dcoEngineId||p.dcoEngineId;a=a.eshopId||p.trackingSetupId;var m=
p.ADFbanID,M=p.unloadID,H=p.geo;p.ptid&&(g+="&ptid="+p.ptid);p.paid&&(g+="&paid="+p.paid);b&&(g+="&icid="+b);a&&(g+="&eid="+a);w&&(g+="&rotseqno="+w);n&&(g+="&smid="+n);t&&(g+="&dco="+t);m&&(g+="&bnrid="+m);M&&(g+="&intid="+M);H&&(g+="&geo="+H);for(var U in D)D[U]+=g;var S={},N,T=0,k=h(100,function(a,d){var k=a*y,b=k+2*y;T=Math.max(T,b);if(N)if(k=N.slice(k,b),k.length)d(null,k,x());else try{throw Error("AdMessage page not found.");}catch(q){d(q)}},function(a){J(t?"recommendations":"adMessage","bn="+
R+"&gcnt="+r+"&pgsz="+Math.min(T,r),function(d,k){if(d)a(d);else if(u(k.items),(N=k.ids)&&N.length)a();else try{throw Error("AdMessage template doesn't contain groups.");}catch(b){a(b)}});T=0}),G={},Q=[],O=h(100,function(a,d){for(var k=a._test||0,b=[],q=0,w=a.length,n,m;q<w;q++)(m=S[n=a[q]])?b.push(m):G[n]||(G[n]=!0,Q.push(n));a._test=++k;if(b.length==a.length)d(null,b,x());else if(4<k)try{throw Error("AdMessage group"+((1<a.length?'s "':' "')+a.join(", "))+'" not found.');}catch(t){d(t)}},function(a){Q.length?
J(t?"products":"adMessage","bn="+R+"&gid="+Q.join(","),function(d,k){G={};d?a(d):(u(k.items),a())}):setTimeout(function(){a()},100);Q=[]});return{setProperties:function(a){var d=a.pageSize>>0||y;a=a.limit>>0||r;0<a&&(r=a);0<d&&(y=Math.min(d,r))},getProperties:x,getPage:function(a,d){k((a>>0)-1,function(a,f){a?d(a):(O(f.slice(0,y),d),O(f.slice(y),e))})},getItems:function(a,d){O(B.isArray(a)?a:[a],d)},getDefault:function(a){O([C],function(d,k,b){a(d,k&&k[0],b)})}}};E.load=function(a,e){var h=B.gid("adform_com_"),
u=x.createElement("script"),p=function(){y();try{throw Error("AdMessage load error.");}catch(a){e(a)}},r=function(a){y();e(null,a)},y=function(){u.parentNode.removeChild(u);z[h]=u.onerror=u.onload=p=r=y=u=null};u.type="text/javascript";u.src=a+"&format=json&callback="+encodeURIComponent(h);u.onload=u.onerror=function(){setTimeout(p,1E3)};z[h]=r;var g=B.byTag(x,"script")[0];g.parentNode.insertBefore(u,g)}})(Adform=window.Adform||{},window,document);
(function(a,z,x,I){function e(){}function h(a){for(var b=r.length;0<b--;)if(r[b][0]==a)return r[b][1]}function v(a,e,x){function d(d){if(d&&v)b(v,"touchstart",J);else if(!v)try{(v=a.defaultView.frameElement)&&g(v,"touchstart",J)}catch(k){}}var q=h(a),n,D,t,m;q?n=q._:r.push([a,q={_:n=new p,_destroy:function(){n.clear();delete this._;delete this._destroy;for(var d in this)if("function"==typeof this[d])this[d]();for(d=r.length;0<d--;)if(r[d][0]==a){r.splice(d,1);break}}}]);var M,H,y,v,N,z,k,G,Q,O;u.isIOS&&
a.defaultView.frameElement&&{click:1,mousedown:1,mouseup:1}[e]&&g(x,e,J);if(!q[e])switch(e){case "swipe":M=function(a){if(y=F(n,a.target,"swipe")[0])a.preventDefault(),(a=a&&a.targetTouches)&&(a=a[0])&&(N=a.pageX,k=a.pageY,Q=(new Date).getTime())};H=function(a){var d=a&&a.targetTouches;y&&(a.preventDefault(),d&&(d=d[0])&&Q&&(z=d.pageX,G=d.pageY,O=(new Date).getTime(),.2<Math.sqrt(Math.pow(z-N,2)+Math.pow(G-k,2))/(O-Q)&&(a=k-G,d={type:"swipe"},d.directionX=0<N-z?"left":"right",d.directionY=0<a?"up":
"down",d.target=y[1],Q=0,B(n,y[1],d))))};g(a,"touchstart",M);g(a,"touchend",H);g(a,"touchmove",H);d();q[e]=function(){b(a,"touchstart",M);b(a,"touchend",H);b(a,"touchmove",H);d(!0)};break;case "hover":a.addEventListener?(D=function(a){a=a.target;m!=a&&E(n,m,m=a)},t=function(a){a=a.relatedTarget;m!=a&&E(n,m,m=a)}):(D=function(d){d=(a.defaultView||a.parentWindow).event.srcElement;m!=d&&E(n,m,m=d)},t=function(d){d=(a.defaultView||a.parentWindow).event.toElement;m!=d&&E(n,m,m=d)});g(a,"mouseover",D);
g(a,"mouseout",t);g(a,"mousemove",D);q[e]=function(){b(a,"mouseover",D);b(a,"mouseout",t);b(a,"mousemove",D);m=null};break;case "click":case "mousedown":case "mouseup":case "touchstart":case "touchmove":case "touchend":D=a.addEventListener?function(a){B(n,a.target,a)}:function(d){d=(a.defaultView||a.parentWindow).event;B(n,d.srcElement,d)},g(a,e,D),q[e]=function(){b(a,e,D)}}return!!q[e]}function E(a,b,e){e=F(a,e,"hover");b=F(a,b,"hover");for(var d=e.length,q=d,n=b.length,g=n-d;0<q--&&e[q][1]==(b[g+
q]&&b[g+q][1]););e.length=d=q+1;b.length=n=g+q+1;var t,m=a._events;if(m){for(g=q=-1;++g<n;)m[t=b[g][0]]&&a.emit(t,b[g][1],"hoverout");for(;++q<d;)m[t=e[q][0]]&&a.emit(t,e[q][1],"hoverin")}}function B(a,b,e,d){d=d||e;b=F(a,b,e.type);e=b.length;for(var q=0,n;n=b[q],q++<e;)a.emit(n[0],n[1],d)}function F(a,b,e){a=a._events;var d,q,n,g=[];if(a)for(;b&&"undefined"!=(n=typeof(q=b.className));)"string"==n&&~q.indexOf("adform-dom-")&&a[d=P(b)+":"+e]&&(g[g.length]=[d,b]),b=b.parentNode;return g}function P(a){a=
a.className;return~a.indexOf("adform-dom-")?a.match(y)[1]:u.gid()}function J(){}a.RMB=a.RMB||{};a=a.RMB;a.DOMEvents=e;var u=a.lib,p=a.EventEmitter,r=[],y=/adform-dom-(\S+)/,g=u.addEvent,b=u.removeEvent;e.has=function(a){return!!{hover:1,mousedown:1,mouseup:1,click:1,swipe:1,touchstart:1,touchmove:1,touchend:1}[a]};e.on=function(a,b,e){var d=a.ownerDocument;if(v(d,b,a)){var q=P(a);u.addClass(a,"adform-dom-"+q);h(d)._.on(q+":"+b,e);return!0}return!1};e.off=function(a,b,e){h(a.ownerDocument)._.off(P(a)+
":"+b,e)};e.destroy=function(a){h(a)._destroy()}})(Adform=window.Adform||{},window,document);
var Mustache="undefined"!==typeof module&&module.exports||{};
(function(a){function z(a){return String(a).replace(/&(?!\w+;)|[<>"']/g,function(a){return R[a]||a})}function x(a,b,n,e){e=e||"<template>";for(var g=b.split("\n"),m=Math.max(n-3,0),g=g.slice(m,Math.min(g.length,n+3)),h,p=0,u=g.length;p<u;++p)h=p+m+1,g[p]=(h===n?" >> ":"    ")+g[p];a.template=b;a.line=n;a.file=e;a.message=[e+":"+n,g.join("\n"),"",a.message].join("\n");return a}function I(a,b,e){if("."===a)return b[b.length-1];a=a.split(".");for(var g=a.length-1,t=a[g],m,h,p=b.length,u,r;p;){r=b.slice(0);
h=b[--p];for(u=0;u<g;){h=h[a[u++]];if(null==h)break;r.push(h)}if(h&&"object"===typeof h&&t in h){m=h[t];break}}"function"===typeof m&&(m=m.call(r[r.length-1]));return null==m?e:m}function e(a,b,e,g){var h="";a=I(a,b);if(g){if(null==a||!1===a||p(a)&&0===a.length)h+=e()}else if(p(a))r(a,function(a){b.push(a);h+=e();b.pop()});else if("object"===typeof a)b.push(a),h+=e(),b.pop();else if("function"===typeof a)var m=b[b.length-1],h=h+(a.call(m,e(),function(a){return B(a,m)})||"");else a&&(h+=e());return h}
function h(d,b){b=b||{};for(var e=b.tags||a.tags,h=e[0],t=e[e.length-1],m=['var buffer = "";',"\nvar line = 1;","\ntry {",'\nbuffer += "'],p=[],u=!1,r=!1,w=function(){if(!u||r||b.space)p=[];else for(;p.length;)m.splice(p.pop(),1);r=u=!1},v=[],z,k,G,Q=function(a){e=g(a).split(/\s+/);k=e[0];G=e[e.length-1]},O=function(a){m.push('";',z,'\nvar partial = partials["'+g(a)+'"];',"\nif (partial) {","\n  buffer += render(partial,stack[stack.length - 1],partials);","\n}",'\nbuffer += "')},f=function(a,k){var f=
g(a);if(""===f)throw x(Error("Section name may not be empty"),d,F,b.file);v.push({name:f,inverted:k});m.push('";',z,'\nvar name = "'+f+'";',"\nvar callback = (function () {","\n  return function () {",'\n    var buffer = "";','\nbuffer += "')},B=function(a){f(a,!0)},E=function(a){a=g(a);var k=0!=v.length&&v[v.length-1].name;if(!k||a!=k)throw x(Error('Section named "'+a+'" was never opened'),d,F,b.file);a=v.pop();m.push('";',"\n    return buffer;","\n  };","\n})();");a.inverted?m.push("\nbuffer += renderSection(name,stack,callback,true);"):
m.push("\nbuffer += renderSection(name,stack,callback);");m.push('\nbuffer += "')},I=function(a){m.push('";',z,'\nbuffer += lookup("'+g(a)+'",stack,"");','\nbuffer += "')},J=function(a){m.push('";',z,'\nbuffer += escapeHTML(lookup("'+g(a)+'",stack,""));','\nbuffer += "')},F=1,C,L,K=0,P=d.length;K<P;++K)if(d.slice(K,K+h.length)===h){K+=h.length;C=d.substr(K,1);z="\nline = "+F+";";k=h;G=t;u=!0;switch(C){case "!":K++;L=null;break;case "=":K++;t="="+t;L=Q;break;case ">":K++;L=O;break;case "#":K++;L=f;
break;case "^":K++;L=B;break;case "/":K++;L=E;break;case "{":t="}"+t;case "&":K++;r=!0;L=I;break;default:r=!0,L=J}C=d.indexOf(t,K);if(-1===C)throw x(Error('Tag "'+h+'" was not closed properly'),d,F,b.file);h=d.substring(K,C);L&&L(h);for(L=0;~(L=h.indexOf("\n",L));)F++,L++;K=C+t.length-1;h=k;t=G}else switch(C=d.substr(K,1),C){case '"':case "\\":r=!0;m.push("\\"+C);break;case "\r":break;case "\n":p.push(m.length);m.push("\\n");w();F++;break;default:y.test(C)?p.push(m.length):r=!0,m.push(C)}if(0!=v.length)throw x(Error('Section "'+
v[v.length-1].name+'" was not closed properly'),d,F,b.file);w();m.push('";',"\nreturn buffer;","\n} catch (e) { throw {error: e, line: line}; }");t=m.join("").replace(/buffer \+= "";\n/g,"");b.debug&&("undefined"!=typeof console&&console.log?console.log(t):"function"===typeof print&&print(t));return t}function v(a,b){var g=h(a,b),p=new Function("view,partials,stack,lookup,escapeHTML,renderSection,render",g);return function(g,h){h=h||{};var n=[g];try{return p(g,h,n,I,z,e,B)}catch(r){throw x(r.error,
a,r.line,b.file);}}}function E(a,b){b=b||{};return!1!==b.cache?(C[a]||(C[a]=v(a,b)),C[a]):v(a,b)}function B(a,b,e){return E(a)(b,e)}a.name="mustache.js";a.version="0.5.0-dev";a.tags=["{{","}}"];a.parse=h;a.compile=E;a.render=B;a.clearCache=function(){C={}};a.to_html=function(a,b,e,g){a=B(a,b,e);if("function"===typeof g)g(a);else return a};var F=Object.prototype.toString,P=Array.isArray,J=Array.prototype.forEach,u=String.prototype.trim,p;p=P?P:function(a){return"[object Array]"===F.call(a)};var r;
r=J?function(a,b,e){return J.call(a,b,e)}:function(a,b,e){for(var g=0,h=a.length;g<h;++g)b.call(e,a[g],g,a)};var y=/^\s*$/,g;if(u)g=function(a){return null==a?"":u.call(a)};else{var b,w;y.test("\u00a0")?(b=/^\s+/,w=/\s+$/):(b=/^[\s\xA0]+/,w=/[\s\xA0]+$/);g=function(a){return null==a?"":String(a).replace(b,"").replace(w,"")}}var R={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},C={}})(Mustache);
(function(a,z,x){function I(){if(z.Ready)for(var a=0;a<Ready.length;a++)v(Ready[a]);z.Ready={push:v}}function e(a,b){var d=n;a&&(d="undefined"==typeof n[a]?b:n[a]);return d}function h(a){a=parseInt(a,10);var b=e("videoSources");if(b)for(var d=b.length,g,f=0;f<d;f++)if(g=b[f],g.id==a)return g.file}function v(a){a.call(z);T||(clearTimeout(N),N=setTimeout(function(){T=!0;x.close()},1E3))}function E(a,b){"function"==typeof b&&(a=b);try{throw Error("AdMessage template id is missing");}catch(d){if("function"==
typeof a)a(d);else throw d;}}function B(a,b,e,g){var f=z._Adform&&_Adform.Events;if(f&&f.sendEvent){if(a in t)b=t[a];else if(isNaN(a=parseInt(a,10))||1>a||20<a&&200>a||250<a)throw Error("Custom event id="+a+" must be between 1-20 for engaging and 200-250 for non-engaging events");if(!b)throw Error("Event name is missing");var h=[""];if(e)for(var m in e){var n=m.slice(0,2),p=parseInt(m.slice(2),10);"bv"==n&&0<p&&256>p&&h.push(m+"="+encodeURIComponent(e[m]))}g&&h.push(g);f.sendEvent(q.xId,a,d.assetId,
b,h.join("&"),"Standard HTML");return!0}return!1}function F(a,b){p[a]||(p[a]=Mustache.compile(P(a).text));if(b){if(y.length!=w){for(var d=0;d<y.length;d++)"text/mustache"==y[d].type&&F(y[d].id);w=y.length}return p[a](b,p)}return p[a]}function P(a){return x.getElementById(a)}for(var J=a.RMB.lib,u=J.isArray,p={},r,y=x.getElementsByTagName("script"),g=0,b;g<y.length;g++)if(b=(y[g].src||"").match(/(^.*)rmb\/Adform\.DHTML\.js/)){r=b[1]+"components/";break}var w=0,R=a.RMB.EventEmitter;b=a.RMB.DOMEvents;
var C=z._AdformContent||{},d=C.data||{},q=C.options||{},n=d.flashvars||{},D=new R;a.on=function(){D.on.apply(D,arguments)};a.off=function(){D.off.apply(D,arguments)};a.emit=function(){D.emit.apply(D,arguments)};var t={151:"Previous Product Button Press",150:"Next Product Button Press",143:"Banner Collapse",22:"Other Expands",21:"First Expand",168:"Auto Expands",161:"Hide Expanding Banner Button Press",23:"Close Button Press",25:"Video Play Start",26:"Played 25% Of Video",27:"Played 50% Of Video",
28:"Played 75% Of Video",29:"Video Playback Complete",30:"Play Button Press",31:"Pause Button Press",32:"Stop Button Press",33:"Sound On Button Press",34:"Sound Off Button Press",35:"Full Screen On Button Press",36:"Full Screen Off Button Press",38:"Rewind Button Press","":""};a.EVENT_FIRST_EXPAND=[21,t[21]];a.EVENT_OTHER_EXPAND=[22,t[22]];a.EVENT_CLOSE=[23,t[23]];a.EVENT_COLLAPSE=[143,t[143]];for(g=1;251>g;g++)if(21>g||199<g)a["EVENT_CUSTOM_"+g]=[g,"Custom Event "+g];a.sendRequest=function(a){(new Image).src=
a};a.sendEvent=function(a){var b,d,e=arguments;if(b=u(a)&&1<a.length){for(b=1;b<e.length&&256>b;b++)(d=d||{})["bv"+b]=e[b];b=B(a[0],a[1],d)}return b};a.getClickURL=function(a,b){return e(a||d.defaultClickTAG||"clickTAG",b)||null};a.getLocation=function(){var a=z._Adform&&_Adform.locationInfo||null;a&&(a.lng=a.Longitude,a.lat=a.Latitude);return a};a.getAsset=function(a){return h(a)||null};a.getVar=function(a){return a&&n[a]?n[a]:null};var m=z.dhtml={PREVIOUS_BUTTON_PRESS:151,NEXT_BUTTON_PRESS:150,
CLOSE_BUTTON_PRESS:23,COLLAPSE_EVENT:143,EXPAND_EVENT:22,FIRST_EXPAND_EVENT:21,AUTO_EXPAND_EVENT:168,SUPER_CLOSE_EVENT:161,VIDEO_PROG_0:25,VIDEO_PROG_25:26,VIDEO_PROG_50:27,VIDEO_PROG_75:28,VIDEO_PROG_100:29,PLAY_BUTTON_PRESS:30,PAUSE_BUTTON_PRESS:31,STOP_BUTTON_PRESS:32,SOUND_ON_BUTTON_PRESS:33,SOUND_OFF_BUTTON_PRESS:34,FULL_SCREEN_ON_BUTTON_PRESS:35,FULL_SCREEN_OFF_BUTTON_PRESS:36,REWIND_BUTTON_PRESS:38,byId:P,hasClass:J.hasClass,addClass:J.addClass,removeClass:J.removeClass,mustache:F,sendEvent:function(a,
b,d){if(!(M&&M.callDHTMLEvent&&M.callDHTMLEvent.call(M,a)))return a in t&&(d=null),B(a,b,d)},$sendEvent:B,appendEvents:function(a){for(var b in a)t.hasOwnProperty(b)||(t[b]=a[b]);return t},getVar:e,getAsset:h,width:d.width,height:d.height,collapsedWidth:q.colWidth,collapsedHeight:q.colHeight,external:C.external||{},inscreen:new R,sharedEvents:C.sharedEvents||new R,scriptsBase:q.scriptsBase||r+"../",getState:function(){return C.state?C.state():"visible"},on:b.on,off:b.off,connect:function(a){var b,
d,e=z._Adform&&_Adform.ADFUtilInstance;a=a||n.bn||"x";e=e?e.getRotSeed():{};e.localConnections||(e.localConnections={});b=e.localConnections[a];b||(b=new R,d=[],b.expect=function(a,e){if(d.length>=a)e();else b.once("expect:"+a,e);return b},b.join=function(a){d.push(a);b.emit("member",a);b.emit("expect:"+d.length);return b},b.members=d,e.localConnections[a]=b);return b}},M;try{M=parent.parent.getVPAIDAd&&parent.parent.getVPAIDAd()}catch(k){}M&&(m.vpaid=M,m.external.close=function(){M.callDHTMLEvent&&
M.callDHTMLEvent.call(M,23)});m.sharedEvents.on("newListener",function(a){"pageLoadComplete"==a&&setTimeout(function(){m.external.initPoliteMode()},0)});m.adMessage=n.tid?a.AdMessage.build({limit:100,pageSize:5}):{setProperties:E,getProperties:E,getPage:E,getItems:E,getDefault:E};var H=m.inscreen;m.external.initInScreen&&(m.sharedEvents.on("updateInScreen",function(a){for(var b in a)H.emit(b,H[b]=a[b]);H.emit("change")}),a.on("newListener",function(b){"visibilityData"===b&&(a.off("newListener",arguments.callee),
H.on("change",function(){a.emit("visibilityData",{isVisible:H.visible,visibleArea:H.percent})}))}),H.once("newListener",function(){setTimeout(function(){m.external.initInScreen()},0)}));components=z.preloadQueue||z.components||[];for(var U=components.length,g=0;g<components.length;g++)x.write('<script src="'+(r+"Adform."+components[g]+".js?bv="+(n.bv||Math.random()))+'">\x3c/script>');try{var S=x.defaultView.frameElement;S&&J.addEvent(S,"touchstart",function(){})}catch(k){}m.registerComponent=function(a){for(var b=
0;b<components.length;b++)components[b]==a&&U--;U||I()};U||I();var N,T})(Adform=window.Adform,window,document);
